entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    tls:
      certificates:
        - certFile: "/certs/fullchain.pem"
          keyFile: "/certs/privkey.pem"

providers:
  docker:
    exposedByDefault: false
